apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-web
  annotations:
      kubernetes.io/tls-acme: 'true' 
      ingress.kubernetes.io/ssl-redirect: "true"
      kubernetes.io/ingress.allow-http: "false"
spec:
  tls:
    - secretName: home-tls
      hosts:
      {{- range $hostname := .Values.hostnames }}
      - {{ $hostname }}
      {{- end }}
  rules:
    {{- range $hostname := .Values.hostnames }}
    - host: {{ $hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $.Values.name }}
                port:
                  number: 8000
    {{- end }}                  